# Generated by Django 4.2.9 on 2024-01-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarkd', '0002_dictionary_url_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='description',
            field=models.TextField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='title',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
